(source gnu)
(source melpa)

(depends-on "auto-complete")
(depends-on "helm")
(depends-on "rust-mode")
(depends-on "racer")
(depends-on "flycheck-rust")
(depends-on "company-racer")
(depends-on "auto-complete-c-headers")
(depends-on "yasnippet")
(depends-on "irony")
(depends-on "rainbow-delimiters")
(depends-on "cl-lib")
(depends-on "color")
(depends-on "elscreen")
(depends-on "color-theme")
